package com.mysanjeevni.mysanjeevni.features.pharmacy.presentation.navigation

sealed class Screen(val route:String) {
    object Splash: Screen("splash")
    object Login: Screen("login")
    object Signup: Screen("signup")
    object Home: Screen("home")
    object Forget :Screen("forget")
    object VERIFY :Screen("verify")
    object ResetPassword :Screen("resetPassword")
    object ProfileScreen :Screen("profile_screen")
    object CartScreen :Screen("cart_screen")
    object Consult : Screen("consult")
    object Health : Screen("health")
    object Plan : Screen("plan")
    object PharmacyList : Screen("pharmacy_list")
    object MyOrders : Screen("my_orders")
    object ManageAddresses : Screen("manage_addresses")
    object EditProfile : Screen("edit_profile")
    object HealthRecords : Screen("health_records")
    object MyLabTestsScreen : Screen("my_lab_tests_screen")
    object SettingScreen : Screen("setting_screen")
    object MyConsultScreen : Screen("my_consult_screen")
    object WalletScreen : Screen("wallet_screen")
    object ReferralScreen : Screen("wallet_screen")
    object TransactionHistoryScreen : Screen("transaction_history_screen")
}